export const ar = {
  common: {
    ok: 'حسناً',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    retry: 'إعادة المحاولة',
    error: 'خطأ',
    warning: 'تحذير',
  },
  app: {
    failedToOpen: 'تعذر فتح التطبيق',
    databaseInitFailed: 'تعذر تهيئة قاعدة البيانات. يرجى إعادة المحاولة.',
  },
  onboarding: {
    title: 'مرحباً بك في دنانير',
    subtitle: 'تحكّم بأموالك بطريقة ذكية وسهلة. تابع مصروفاتك، افهم دخلك، وحقق أهدافك المالية بثقة وأمان.',
    createAccount: 'إنشاء حساب جديد',
    signIn: 'تسجيل الدخول',
    continueAsGuest: 'التخطي والاستمرار كضيف',
    footer: 'بذكاء، تدير دنانير حياتك المالية',
  },
  navigation: {
    settings: 'الإعدادات',
    analytics: 'التحليلات',
    transactions: 'المعاملات',
    home: 'الرئيسية',
    expenses: 'المصاريف',
    income: 'الدخل',
    financialTransactions: 'المعاملات المالية',
    financialAnalysis: 'التحليل المالي',
    smartInsights: 'رؤى ذكية',
    advancedReports: 'التقارير المتطورة',
    profile: 'الملف الشخصي',
    goals: 'الأهداف المالية',
    savings: 'الحصالة - توفير مالي',
    goalPlan: 'خطة الهدف',
    budget: 'الميزانية',
    currencyConverter: 'محول العملات',
    debtsAndInstallments: 'الديون والأقساط',
    debtDetails: 'تفاصيل الدين',
    accountDetails: 'تفاصيل الحساب',
    bills: 'الفواتير',
    billDetails: 'تفاصيل الفاتورة',
    achievements: 'الإنجازات',
    challenges: 'التحديات',
    notifications: 'الإشعارات',
    aiInsights: 'التحليلات الذكية',
    calendar: 'التقويم المالي',
    wallets: 'المحافظ',
  },
  auth: {
    login: 'تسجيل الدخول',
    loginRequiredTitle: 'تسجيل الدخول',
    loginRequiredForAi: 'يجب تسجيل الدخول أو إنشاء حساب لاستخدام التحليل الذكي.',
    loginTryAgain: 'حدث خطأ. تأكد من تسجيل الدخول وحاول مرة أخرى.',
  },
  sync: {
    premiumTitle: 'اشتراك مميز',
    premiumMessage: 'مزامنة البيانات متاحة للمشتركين المميزين فقط. يجب أن يكون نوع حسابك أو اشتراكك مميزاً لاستخدام المزامنة.',
    noNewData: 'لا توجد بيانات جديدة',
    uploadedItems: 'تم رفع {{count}} عنصر',
    failedTitle: 'فشل المزامنة',
  },
  settings: {
    languageAndCurrency: 'اللغة والعملة',
    baseCurrency: 'العملة الأساسية',
    appLanguage: 'لغة التطبيق',
    languageChanged: 'تم تغيير لغة التطبيق إلى {{language}}',
    languageChangeFailed: 'تعذر حفظ اللغة الجديدة. حاول مرة أخرى.',
    notificationsPermissionTitle: 'إذن مطلوب',
    notificationsPermissionMessage: 'يرجى السماح بالإشعارات من إعدادات التطبيق',
    autoSyncPremiumMessage: 'المزامنة التلقائية متاحة للمشتركين المميزين فقط. يجب أن يكون نوع حسابك أو اشتراكك مميزاً.',
    currencyChanged: 'تم تغيير العملة إلى {{currency}}',
  },
} as const;
