export const en = {
  common: {
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
    retry: 'Retry',
    error: 'Error',
    warning: 'Warning',
  },
  app: {
    failedToOpen: 'Unable to open the app',
    databaseInitFailed: 'Unable to initialize the database. Please try again.',
  },
  onboarding: {
    title: 'Welcome to Dnanir',
    subtitle: 'Take control of your money in a smart and simple way. Track expenses, understand income, and reach your financial goals with confidence.',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    continueAsGuest: 'Skip and Continue as Guest',
    footer: 'Manage your financial life smarter with Dnanir',
  },
  navigation: {
    settings: 'Settings',
    analytics: 'Analytics',
    transactions: 'Transactions',
    home: 'Home',
    expenses: 'Expenses',
    income: 'Income',
    financialTransactions: 'Financial Transactions',
    financialAnalysis: 'Financial Analysis',
    smartInsights: 'Smart Insights',
    advancedReports: 'Advanced Reports',
    profile: 'Profile',
    goals: 'Financial Goals',
    savings: 'Savings Wallet',
    goalPlan: 'Goal Plan',
    budget: 'Budget',
    currencyConverter: 'Currency Converter',
    debtsAndInstallments: 'Debts & Installments',
    debtDetails: 'Debt Details',
    accountDetails: 'Account Details',
    bills: 'Bills',
    billDetails: 'Bill Details',
    achievements: 'Achievements',
    challenges: 'Challenges',
    notifications: 'Notifications',
    aiInsights: 'AI Insights',
    calendar: 'Financial Calendar',
  },
  auth: {
    login: 'Sign In',
    loginRequiredTitle: 'Sign In',
    loginRequiredForAi: 'You need to sign in or create an account to use smart analysis.',
    loginTryAgain: 'Something went wrong. Please make sure you are signed in and try again.',
  },
  sync: {
    premiumTitle: 'Premium Subscription',
    premiumMessage: 'Data sync is available for premium users only. Your account or subscription must be premium to use sync.',
    noNewData: 'No new data',
    uploadedItems: 'Uploaded {{count}} item(s)',
    failedTitle: 'Sync Failed',
  },
  settings: {
    languageAndCurrency: 'Language & Currency',
    baseCurrency: 'Base Currency',
    appLanguage: 'App Language',
    languageChanged: 'App language changed to {{language}}',
    languageChangeFailed: 'Unable to save the new language. Please try again.',
    notificationsPermissionTitle: 'Permission Required',
    notificationsPermissionMessage: 'Please allow notifications from the app settings',
    autoSyncPremiumMessage: 'Auto sync is available for premium users only. Your account or subscription must be premium.',
    currencyChanged: 'Currency changed to {{currency}}',
  },
} as const;
