import { literalAr } from './literal-ar';

const exactLiteralEn: Record<string, string> = {
  '— تطبيق دنانير': 'Dnanir App',
  '({{}} معروض)': '({{}} shown)',
  '(*** معروض)': '(*** shown)',
  '(مدفوع)': '(Paid)',
  '{{}} {{}} هل تريد إضافة هذا الدخل؟': 'Do you want to add this income: {{}} {{}}?',
  '{{}} {{}} هل تريد إضافة هذا المصروف؟': 'Do you want to add this expense: {{}} {{}}?',
  '{{}} عملية {{}}': '{{}} transaction {{}}',
  '{{}} مصروف {{}}': '{{}} expense {{}}',
  '{{}} يوم': '{{}} day',
  '{{}} يوم متبقي': '{{}} day left',
  '{{}}، {{}}': '{{}}, {{}}',
  '{{}}، {{}}{{}}، {{}}': '{{}}, {{}} {{}} {{}}',
  '{{}}% مستخدم': '{{}}% used',
  '{{}}% من إجمالي الأهداف': '{{}}% of total goals',
  '*** عملية {{}}': '*** transaction {{}}',
  '*** مصروف {{}}': '*** expense {{}}',
  '**% مستخدم': '**% used',
  '% مكتمل': '% complete',
  '© 2025 URUX. جميع الحقوق محفوظة.': '© 2025 URUX. All rights reserved.',
  'آخر تحديث:': 'Last updated:',
  'ابدأ التحليل الآن': 'Start analysis now',
  'ابدأ بإنشاء حصالة جديدة لتوفير المال لأهدافك المختلفة': 'Start by creating a new savings wallet for your different goals',
  'ابدأ بتحدي جديد لتحسين عاداتك المالية': 'Start a new challenge to improve your financial habits',
  'ابدأ بتحديد هدف مالي جديد واتبع تقدمك نحو تحقيقه': 'Set a new financial goal and track your progress toward reaching it',
  'أبريل': 'April',
  'اتجاه الدين': 'Debt direction',
  'إجمالي الإيرادات': 'Total revenue',
  'إجمالي الدخل': 'Total income',
  'إجمالي الفواتير غير المدفوعة': 'Total unpaid bills',
  'إجمالي المبلغ': 'Total amount',
  'إجمالي المدخرات': 'Total savings',
  'إجمالي المدفوعات': 'Total payments',
  'إجمالي المصاريف': 'Total expenses',
  'إجمالي الميزانية': 'Total budget',
  'أحدث العمليات': 'Latest transactions',
  'اختر الأيقونة': 'Choose an icon',
  'اختر التاريخ': 'Choose a date',
  'اختر الدولة': 'Choose a country',
  'اختر الفئة': 'Choose a category',
  'اختر اللون': 'Choose a color',
  'اختر الوقت': 'Choose a time',
  'اختر الوقت:': 'Choose a time:',
  'اختر تحدياً جديداً': 'Choose a new challenge',
  'اختر مصدر الصورة': 'Choose image source',
  'اختر ملف نسخة احتياطية من جهازك (ملف أو iCloud)': 'Choose a backup file from your device (Files or iCloud)',
  'اختصارات ذكية': 'Smart shortcuts',
  'اختصارات سريعة': 'Quick shortcuts',
  'إخفاء المقارنة': 'Hide comparison',
  'إدارة': 'Manage',
  'إدارة الحساب، المزامنة، والإحالة': 'Manage account, sync, and referrals',
  'إدارة فئات المصاريف': 'Manage expense categories',
  'إدارة مصادر الدخل': 'Manage income sources',
  'إدخال صوتي': 'Voice input',
  'إدخال يدوي': 'Manual entry',
  'أدخل اسم الفئة': 'Enter category name',
  'أدخل اسمك': 'Enter your name',
  'أدخل الاسم...': 'Enter the name...',
  'أدخل التفاصيل بنفسك': 'Enter the details yourself',
  'أدخل الرمز المرسل إلى {{}}': 'Enter the code sent to {{}}',
  'أدخل الرمز المكون من 6 أرقام المرسل إلى': 'Enter the 6-digit code sent to',
  'أدخل رقم هاتفك لاستعادة حسابك': 'Enter your phone number to recover your account',
  'أدخل سعر الصرف الحالي للدولار مقابل': 'Enter the current exchange rate for the dollar against',
  'أدخل كلمة المرور للفتح': 'Enter the password to unlock',
  'ادعُ أصدقاءك واكسب "برو"': 'Invite your friends and earn Pro',
  'إذن مطلوب': 'Permission required',
  'إرسال رمز التحقق': 'Send verification code',
  'أسبوعياً': 'Weekly',
  'استخدام كود برومو (Promo Code)': 'Use promo code',
  'استخدم {{}} للفتح': 'Use {{}} to unlock',
  'استخدم كود الإحالة الخاص بي ({{}}) في تطبيق "دنانير" لتحصل على 7 أيام اشتراك برو مجاناً! حمل التطبيق من هنا: {{}}': 'Use my referral code ({{}}) in Dnanir to get 7 free days of Pro! Download the app here: {{}}',
  'استشارة AI': 'AI consultation',
  'استعادة': 'Restore',
  'استعادة من السيرفر': 'Restore from server',
  'استعادة من ملف': 'Restore from file',
  'استمر في استخدام التطبيق لفتح الإنجازات': 'Keep using the app to unlock achievements',
  'اسم الحصالة (عمرة، سيارة...)': 'Savings wallet name (Umrah, car...)',
  'اسم الدائن': 'Creditor name',
  'اسم الدائن أو الشخص': 'Creditor or person name',
  'اسم الفئة': 'Category name',
  'اسم المدين': 'Debtor name',
  'اسم المدين (من يستحق عليه)': 'Debtor name (who owes it)',
  'اشتراك مميز': 'Premium subscription',
  'إضافة': 'Add',
  'إضافة البيانات الجديدة للسيرفر (مميز)': 'Upload new data to server (Premium)',
  'إضافة التزام جديد': 'Add new obligation',
  'إضافة إيراد جديد': 'Add new income',
  'إضافة دخل': 'Add income',
  'إضافة صورة الفاتورة': 'Add bill image',
  'إضافة فئة جديدة': 'Add new category',
  'إضافة مصدر جديد': 'Add new source',
  'إضافة مصروف': 'Add expense',
  'إضافة مصروف جديد': 'Add new expense',
  'إضافة ميزانية جديدة': 'Add new budget',
  'إضافة هدف جديد': 'Add new goal',
  'اضغط الزر أعلاه للحصول على خطة ونصائح لتحقيق هذا الهدف بالذكاء الاصطناعي.': 'Tap the button above to get an AI plan and tips for this goal.',
  'اضغط للمصادقة بـ': 'Tap to authenticate with',
  'أضف أول دين أو قسط أو سلفة لتتبعها هنا': 'Add your first debt, installment, or advance to track it here',
  'أضف ديناً جديداً لارتباطه بشخص ما': 'Add a new debt linked to a person',
  'أضف عملية الآن': 'Add a transaction now',
  'أضف فئات جديدة لتسهيل تصنيف مصاريفك': 'Add new categories to organize your expenses',
  'أضف فئة جديدة للمصاريف': 'Add a new expense category',
  'أضف فاتورة جديدة للبدء': 'Add a new bill to get started',
  'أضف مصادر دخل جديدة لتسهيل تصنيف دخلك': 'Add new income sources to organize your income',
  'أضف مصدر دخل جديد': 'Add a new income source',
  'أضف مصروف متكرر لتتبعه تلقائياً': 'Add a recurring expense to track it automatically',
  'أضف ملاحظات حول هدفك...': 'Add notes about your goal...',
  'أضف ميزانية جديدة لتتبع إنفاقك': 'Add a new budget to track your spending',
  'أضيف من الاختصار': 'Add from shortcut',
  'إعادة إرسال الرمز': 'Resend code',
  'إعادة الإرسال بعد {{}} ثانية': 'Resend after {{}} seconds',
  'إعادة إنشاء الخطة': 'Regenerate plan',
  'إعادة تحليل البيانات': 'Reanalyze data',
  'إعادة فتح': 'Reopen',
  'إعدادات الإشعارات': 'Notification settings',
  'أعلى المصاريف': 'Top expenses',
  'أغسطس': 'August',
  'إغلاق': 'Close',
  'أقساط': 'Installments',
  'اكتشف أنماط إنفاقك واحصل على توجيهات استراتيجية لنموك المالي.': 'Discover your spending patterns and get strategic guidance for your financial growth.',
  'أكتوبر': 'October',
  'إكمال': 'Complete',
  'إكمال التحدي': 'Complete challenge',
  'الادخار الشهري المقترح': 'Suggested monthly savings',
  'الاسم': 'Name',
  'الاسم الكامل': 'Full name',
  'الأشخاص': 'People',
  'الإشعارات': 'Notifications',
  'الإعدادات العامة': 'General settings',
  'الأقساط': 'Installments',
  'الإنجازات': 'Achievements',
  'الإنجازات المفتوحة': 'Unlocked achievements',
  'الإنجازات المقفلة': 'Locked achievements',
  'الأهداف': 'Goals',
  'الأهداف المنجزة': 'Completed goals',
  'الأهداف النشطة': 'Active goals',
  'الأيقونة': 'Icon',
  'البريد الإلكتروني': 'Email',
  'التالي:': 'Next:',
  'التحديات المكتملة': 'Completed challenges',
  'التحديات النشطة': 'Active challenges',
  'التحدي': 'Challenge',
  'التحليل الذكي': 'Smart analysis',
  'التحليل الذكي والتقارير': 'Smart analysis and reports',
  'التحليل الذكي يستهلك محاولة من حدك الشهري. هل تريد المتابعة؟': 'Smart analysis uses one attempt from your monthly limit. Do you want to continue?',
  'التصدير': 'Export',
  'التصنيف': 'Category',
  'التطبيق محمي': 'App is protected',
  'التفاصيل': 'Details',
  'التقاط صورة': 'Take photo',
  'التقويم': 'Calendar',
  'التوقعات المالية': 'Financial forecasts',
  'الحالة': 'Status',
  'الحساب': 'Account',
  'الحساب والملف الشخصي': 'Account and profile',
  'الحصالة': 'Savings wallet',
  'الخروج من الحساب الحالي': 'Sign out of the current account',
  'الدخل': 'Income',
  'الدخل:': 'Income:',
  'الدخل: {{}}': 'Income: {{}}',
  'الدين': 'Debt',
  'الديون': 'Debts',
  'الرصيد': 'Balance',
  'الرصيد المتبقي المتوقع:': 'Expected remaining balance:',
  'السنة': 'Year',
  'الشهر': 'Month',
  'الشهر المحدد': 'Selected month',
  'الصافي': 'Net',
  'الصافي: {{}}': 'Net: {{}}',
  'العمليات': 'Transactions',
  'العملية': 'the process',
  'إلغاء': 'Cancel',
  'إلغاء حالة الدفع': 'Mark as unpaid',
  'الفئات': 'Categories',
  'الفئة': 'Category',
  'الفلاتر': 'Filters',
  'الفاتورة': 'Bill',
  'الفواتير': 'Bills',
  'الكل': 'All',
  'الكود المخصص لك:': 'Your referral code:',
  'اللون': 'Color',
  'المبلغ': 'Amount',
  'المبلغ الحالي:': 'Current amount:',
  'المبلغ الشهري': 'Monthly amount',
  'المبلغ المستهدف': 'Target amount',
  'المتبقي': 'Remaining',
  'المجموع': 'Total',
  'المحاولات: {{}} (وصول لامحدود ♾️)': 'Attempts: {{}} (Unlimited access ♾️)',
  'المحاولات: {{}} مستهلكة، {{}} متبقية من {{}}': 'Attempts: {{}} used, {{}} remaining out of {{}}',
  'المحقق': 'Achieved',
  'المزامنة التلقائية متاحة للمشتركين المميزين فقط. يجب أن يكون نوع حسابك أو اشتراكك مميزاً.': 'Auto sync is available for premium users only. Your account or subscription must be premium.',
  'المستهدف': 'Target',
  'المصاريف': 'Expenses',
  'المصاريف: {{}}': 'Expenses: {{}}',
  'المصدر': 'Source',
  'المصروف': 'Expense',
  'المصروف:': 'Expense:',
  'المظهر (Theme)': 'Theme',
  'الهدف': 'Goal',
  'البيانات': 'Data',
  'الميزانية': 'Budget',
  'النسخ الاحتياطي والاستعادة': 'Backup and restore',
  'النظام': 'System',
  'الوضع المالي': 'Financial status',
  'إلى': 'To',
  'إلى تاريخ': 'To date',
  'الإيراد': 'Income entry',
  'اليوم': 'Today',
  'انتهت المحاولات': 'No attempts left',
  'انتهى': 'Ended',
  'إنجاز': 'Achievement',
  'أنشئ تحدياً خاصاً بك': 'Create your own challenge',
  'أنشئ كلمة مرور قوية جديدة': 'Create a strong new password',
  'إنشاء الحساب': 'Create account',
  'إنشاء الحصالة': 'Create savings wallet',
  'إنشاء الخطة الآن': 'Create plan now',
  'إنشاء تقرير شامل لجميع المعاملات': 'Create a full report for all transactions',
  'إنشاء حساب': 'Create account',
  'إنشاء حساب / دخول': 'Create account / Sign in',
  'إنشاء حساب جديد': 'Create a new account',
  'إنشاء حصالة الآن': 'Create a savings wallet now',
  'أهلاً بك في دنانير': 'Welcome to Dnanir',
  'أو استخدم': 'Or use',
  'أيام': 'Days',
  'بحث عن دولة أو رمز...': 'Search for a country or code...',
  'بداية الالتزام:': 'Start date:',
  'برنامج الإحالة': 'Referral program',
  'بناءً على عاداتك الشرائية': 'Based on your spending habits',
  'بيانات الاستحقاق': 'Due details',
  'تاريخ الاستحقاق': 'Due date',
  'تاريخ الاستحقاق:': 'Due date:',
  'تاريخ البدء': 'Start date',
  'تاريخ الهدف': 'Goal date',
  'تأكد من الفلاتر أو أضف إيراداً جديداً': 'Check the filters or add a new income entry',
  'تأكد من الفلاتر أو أضف مصروفاً جديداً': 'Check the filters or add a new expense entry',
  'تأكيد': 'Confirm',
  'تأكيد إضافة دخل': 'Confirm adding income',
  'تأكيد إضافة مصروف': 'Confirm adding expense',
  'تأكيد التحليل': 'Confirm analysis',
  'تأكيد الحذف': 'Confirm deletion',
  'تأكيد كلمة المرور': 'Confirm password',
  'تحدث وسنسجل لك': 'Speak and we will log it for you',
  'تحدي مخصص': 'Custom challenge',
  'تحديات نشطة': 'Active challenges',
  'تحديث': 'Update',
  'تحديث البيانات': 'Update data',
  'تحديث التقدم': 'Update progress',
  'تحديث الحصالة': 'Update savings wallet',
  'تحديث الدخل': 'Update income',
  'تحديث الفاتورة': 'Update bill',
  'تحديث المصروف': 'Update expense',
  'تحديث الميزانية': 'Update budget',
  'تحديث الهدف': 'Update goal',
  'تحديث تلقائي': 'Auto update',
  'تحذير': 'Warning',
  'تحقق من الرمز': 'Verify the code',
  'تحقق وتسجيل': 'Verify and register',
  'تحليل البيانات الآن': 'Analyze data now',
  'تحليل الفئات': 'Category analysis',
  'تحليل المصروفات': 'Expense analysis',
  'تحليل ذكي': 'Smart analysis',
  'تحليلات ذكية': 'Smart insights',
  'تذكرت كلمة المرور؟': 'Remembered your password?',
  'تذكير قبل': 'Reminder before',
  'تذكير يومي': 'Daily reminder',
  'تذكير يومي لتسجيل المصاريف': 'Daily reminder to log expenses',
  'تسجيل الخروج': 'Sign out',
  'تسجيل الدخول': 'Sign in',
  'تسجيل الدفع الآن': 'Record payment now',
  'تسجيل دفعة مستلمة': 'Record received payment',
  'تصدير البيانات': 'Export data',
  'تصدير الكل': 'Export all',
  'تصدير بيانات الشهر المحدد والشهر الذي يسبقه': 'Export data for the selected month and the month before it',
  'تصدير بيانات شهر': 'Export one month of data',
  'تصدير CSV': 'Export CSV',
  'تصدير PDF': 'Export PDF',
  'تعديل': 'Edit',
  'تعديل الاسم': 'Edit name',
  'تعديل البيانات': 'Edit details',
  'تعديل التزام': 'Edit obligation',
  'تعديل الحصالة': 'Edit savings wallet',
  'تعديل الفئة': 'Edit category',
  'تعديل الميزانية': 'Edit budget',
  'تعديل الهدف': 'Edit goal',
  'تعديل دخل': 'Edit income',
  'تعديل سعر الصرف': 'Edit exchange rate',
  'تعديل فاتورة': 'Edit bill',
  'تعديل مصروف': 'Edit expense',
  'تعذر إنشاء تقرير PDF حالياً': 'Unable to create a PDF report right now',
  'تعذر مشاركة الملخص حالياً': 'Unable to share the summary right now',
  'تغيير تفاصيل الميزانية أو المبلغ': 'Change the budget details or amount',
  'تغيير كلمة المرور': 'Change password',
  'تقائياً كل شهر': 'Automatically every month',
  'تقرير شهري': 'Monthly report',
  'تكرار الفاتورة': 'Bill recurrence',
  'تكرار القسط': 'Installment recurrence',
  'تلقائياً كل أسبوع': 'Automatically every week',
  'تلقي تنبيهات حول المصاريف والأهداف': 'Receive alerts about expenses and goals',
  'تم إرسال رمز التحقق': 'Verification code sent',
  'تم إرسال رمز تجريبي في وضع التطوير': 'A test code was sent in development mode',
  'تم استعادة البيانات من السيرفر.': 'Data restored from the server.',
  'تم استعادة النسخة الاحتياطية من الملف.': 'Backup restored from file.',
  'تم إضافة التحدي المخصص بنجاح': 'Custom challenge added successfully',
  'تم إضافة التحدي بنجاح': 'Challenge added successfully',
  'تم إضافة الدخل': 'Income added',
  'تم إضافة المصروف': 'Expense added',
  'تم إعادة إرسال رمز التحقق': 'Verification code resent',
  'تم إعادة فتح التحدي': 'Challenge reopened',
  'تم إكمال التحدي بنجاح! 🎉': 'Challenge completed successfully! 🎉',
  'تم الحذف بنجاح': 'Deleted successfully',
  'تم الفتح:': 'Unlocked:',
  'تم إنجاز الهدف': 'Goal completed',
  'تم إنشاء الحساب بنجاح': 'Account created successfully',
  'تم إنشاء الحصالة بنجاح': 'Savings wallet created successfully',
  'تم إنشاء النسخة الاحتياطية بنجاح. يمكنك حفظ الملف في التخزين أو مشاركته.': 'Backup created successfully. You can save the file or share it.',
  'تم تحديث التحدي بنجاح': 'Challenge updated successfully',
  'تم تحديث التقدم': 'Progress updated',
  'تم تحديث الدخل': 'Income updated',
  'تم تحديث المصروف': 'Expense updated',
  'تم تحديث حالة الفاتورة': 'Bill status updated',
  'تم تسجيل التسديد بالكامل وتمت إضافته لرصيدك': 'Full payment recorded and added to your balance',
  'تم تسجيل الخروج بنجاح': 'Signed out successfully',
  'تم تسجيل الدخول بنجاح': 'Signed in successfully',
  'تم تسجيل تسديد {{}} وتمت إضافته لرصيدك': 'Payment of {{}} recorded and added to your balance',
  'تم تسجيل تسديد القسط وإضافته لرصيدك': 'Installment payment recorded and added to your balance',
  'تم تسجيل عملية التسديد': 'Payment recorded',
  'تم تصدير التقرير بنجاح': 'Report exported successfully',
  'تم تعيين وقت تذكير المصاريف إلى {{}}': 'Expense reminder time set to {{}}',
  'تم تغيير العملة إلى {{}}': 'Currency changed to {{}}',
  'تم تغيير كلمة المرور بنجاح، يمكنك الآن تسجيل الدخول': 'Password changed successfully. You can sign in now',
  'تم حفظ الوقت لكن فشل جدولة التذكير': 'Time saved, but scheduling the reminder failed',
  'تم حفظ سعر الصرف بنجاح': 'Exchange rate saved successfully',
  'تم حفظ وقت التذكير اليومي: {{}}': 'Daily reminder time saved: {{}}',
  'تم دفع {{}} بنجاح': '{{}} paid successfully',
  'تم دفع الدين بالكامل بنجاح': 'Debt paid in full successfully',
  'تم دفع الفاتورة': 'Bill paid',
  'تم دفع الفاتورة بنجاح': 'Bill paid successfully',
  'تم دفع القسط بنجاح': 'Installment paid successfully',
  'تم دفع:': 'Paid:',
  'تم رفع {{}} عنصر': '{{}} item(s) uploaded',
  'تم سحب المبلغ بنجاح': 'Amount withdrawn successfully',
  'تم تحويل المبلغ بنجاح': 'Amount transferred successfully',
  'تم نسخ الكود': 'Code copied',
  'تم نسخ معرف المستخدم': 'User ID copied',
  'تمت إضافة {{}} عنصر جديد': '{{}} new item(s) added',
  'تمت إضافة الدخل: {{}}': 'Income added: {{}}',
  'تمت إضافة المبلغ بنجاح': 'Amount added successfully',
  'تمت إضافة المصروف: {{}}': 'Expense added: {{}}',
  'تنبيه': 'Notice',
  'تنبيهات الدفع': 'Payment alerts',
  'تنبيهات هامة': 'Important alerts',
  'تواصل معنا': 'Contact us',
  'تواصل معنا عبر WhatsApp': 'Contact us via WhatsApp',
  'توزيع الفئات': 'Category distribution',
  'توقعات الشهر القادم': 'Next month forecast',
  'جاري التحميل...': 'Loading...',
  'جاري التحويل...': 'Converting...',
  'جاري الحفظ...': 'Saving...',
  'جاري المزامنة...': 'Syncing...',
  'جاري تحليل بياناتك...': 'Analyzing your data...',
  'جاري تهيئة الرؤى الذكية...': 'Preparing smart insights...',
  'جديدة': 'New',
  'جرب تغيير الفلتر': 'Try changing the filter',
  'جرب تغيير الفلتر للحصول على نتائج': 'Try changing the filter to get results',
  'جلب آخر نسخة من السيرفر واستبدال البيانات المحلية (مميز)': 'Fetch the latest copy from the server and replace local data (Premium)',
  'جميع البيانات': 'All data',
  'جميع الفئات': 'All categories',
  'جميع المصادر': 'All sources',
  'حدث خطأ': 'Something went wrong',
  'حدث خطأ. تأكد من تسجيل الدخول وحاول مرة أخرى.': 'Something went wrong. Make sure you are signed in and try again.',
  'حدد موعد لتحقيق هدفك': 'Set a date to achieve your goal',
  'حذف': 'Delete',
  'حذف الالتزام': 'Delete obligation',
  'حذف التحدي': 'Delete challenge',
  'حذف الحساب': 'Delete account',
  'حذف الدين': 'Delete debt',
  'حذف الصورة': 'Delete image',
  'حذف الفئة': 'Delete category',
  'حذف الفاتورة': 'Delete bill',
  'حذف الكل': 'Delete all',
  'حذف المصروف المتكرر': 'Delete recurring expense',
  'حذف جميع البيانات': 'Delete all data',
  'حذف جميع البيانات؟': 'Delete all data?',
  'حذف هذه الميزانية نهائياً': 'Delete this budget permanently',
  'حساب مميز': 'Premium account',
  'حساب موثق': 'Verified account',
  'حسابي والأمان': 'My account and security',
  'حسناً': 'OK',
  'حصالات نشطة': 'active savings wallets',
  'حصالاتي': 'My savings wallets',
  'حصالة جديدة': 'New savings wallet',
  'حفظ': 'Save',
  'حفظ الالتزام': 'Save obligation',
  'حفظ التغييرات': 'Save changes',
  'حفظ الدخل': 'Save income',
  'حفظ الفاتورة': 'Save bill',
  'حفظ المصروف': 'Save expense',
  'حفظ الميزانية': 'Save budget',
  'حفظ الهدف': 'Save goal',
  'حفظ كل بياناتك في ملف واحفظه على جهازك': 'Save all your data in one file and keep it on your device',
  'خطأ': 'Error',
  'خطة الهدف بالذكاء الاصطناعي متوفرة للحسابات المميزة فقط. يجب أن يكون نوع حسابك أو اشتراكك مميزاً لاستخدامها.': 'AI goal planning is available for premium accounts only. Your account or subscription must be premium to use it.',
  'خطوات الخطة': 'Plan steps',
  'خطوات تحسين مقترحة': 'Suggested improvement steps',
  'خطواتك نحو النجاح المالي': 'Your steps toward financial success',
  'خيارات الميزانية': 'Budget options',
  'خيارات تصدير PDF': 'PDF export options',
  'د.ع': 'IQD',
  'داكن': 'Dark',
  'دخل جديد': 'New income',
  'دخول / تسجيل': 'Sign in / Register',
  'دفع': 'Pay',
  'دفع على شكل أقساط؟': 'Pay in installments?',
  'دفع مبلغ من الدين': 'Pay part of the debt',
  'دقة عالية': 'High quality',
  'دقة متوسطة': 'Medium quality',
  'دنانير - تطبيق المالية الشخصية': 'Dnanir - Personal Finance App',
  'ديسمبر': 'December',
  'دين': 'Debt',
  'رؤى وتوصيات مالية': 'Financial insights and recommendations',
  'رسالة الخطة': 'Plan message',
  'رصيد صفر': 'Zero balance',
  'رصيدك الحالي:': 'Your current balance:',
  'رقم الهاتف': 'Phone number',
  'رقم الهاتف (اختياري)': 'Phone number (optional)',
  'رمز التحقق': 'Verification code',
  'سبتمبر': 'September',
  'سجل المدفوعات': 'Payment history',
  'سجل إنجازاتك': 'Track your achievements',
  'سجل دخولك لمزامنة بياناتك والحصول على ميزات إضافية': 'Sign in to sync your data and unlock extra features',
  'سجل عمليات الدفع': 'Payment records',
  'سعر الصرف': 'Exchange rate',
  'سعر الصرف (1 دولار = ?': 'Exchange rate (1 USD = ?',
  'سلفة': 'Advance',
  'سنوياً': 'Yearly',
  'سيتم استبدال كل بياناتك المحلية بآخر نسخة من السيرفر. هل أنت متأكد؟': 'All your local data will be replaced with the latest server copy. Are you sure?',
  'سيتم تحديث الرؤى فور الانتهاء': 'Insights will update as soon as it is done',
  'سيتم حذف كافة المصاريف والأهداف والديون بشكل نهائي. هل أنت متأكد من رغبتك في المتابعة؟': 'All expenses, goals, and debts will be deleted permanently. Are you sure you want to continue?',
  'سيتم مسح كافة البيانات بشكل نهائي.': 'All data will be erased permanently.',
  'شارك رابط تيليجرام عبر واتساب أو أي تطبيق': 'Share the Telegram link via WhatsApp or any app',
  'شارك رابط App Store عبر واتساب أو أي تطبيق': 'Share the App Store link via WhatsApp or any app',
  'شهري': 'Monthly',
  'شهرياً': 'Monthly',
  'شهرين معاً': 'Two months together',
  'ص': 'AM',
  'صافي - علي': 'Net - I owe',
  'صافي - لي': 'Net - owed to me',
  'صافي الرصيد المتبقي لـ:': 'Net remaining balance for:',
  'عدد الإحالات الناجحة:': 'Successful referrals:',
  'عدد الأقساط': 'Number of installments',
  'عدد المعاملات': 'Number of transactions',
  'عرض المرفق': 'View attachment',
  'عرض المزيد': 'Show more',
  'عضو مميز': 'Premium member',
  'علي': 'I owe',
  'عمليات •': 'Transactions •',
  'عمليات يوم': 'Transactions for',
  'عنوان الفاتورة (مثال: فاتورة الكهرباء)': 'Bill title (e.g. electricity bill)',
  'عنوان الهدف': 'Goal title',
  'غير مدفوعة': 'unpaid',
  'غير نشط': 'Inactive',
  'فئة افتراضية': 'Default category',
  'فئة مخصصة': 'Custom category',
  'فاتح': 'Light',
  'فاتورة جديدة': 'New bill',
  'فاتورة متكررة': 'Recurring bill',
  'فبراير': 'February',
  'فشل الاستعادة': 'Restore failed',
  'فشل المزامنة': 'Sync failed',
  'فشل تحديث الاسم': 'Failed to update the name',
  'فشل تحديث البيانات': 'Failed to update the data',
  'فشل تحميل بيانات الإحالة. يرجى سحب الصفحة للتحديث.': 'Failed to load referral data. Please pull down to refresh.',
  'فشل تسجيل الخروج': 'Failed to sign out',
  'فشل تصدير التقرير': 'Failed to export the report',
  'فشل جدولة التذكير اليومي': 'Failed to schedule the daily reminder',
  'فشل جدولة تذكير المصاريف': 'Failed to schedule the expense reminder',
  'فشل حذف الحساب': 'Failed to delete the account',
  'فشل حفظ الحصالة': 'Failed to save the savings wallet',
  'فشل حفظ وقت التذكير اليومي': 'Failed to save the daily reminder time',
  'فشل في تسجيل التسديد': 'Failed to record the payment',
  'فشل في تحميل الرؤى': 'Failed to load insights',
  'قريباً': 'soon',
  'قم بتحليل بياناتك المالية للحصول على رؤى عميقة وتوقعات دقيقة لميزانيتك.': 'Analyze your financial data to get deep insights and accurate budget forecasts.',
  'قم بتعديل بيانات فئة المصاريف': 'Edit the expense category details',
  'قم بتعديل بيانات مصدر الدخل': 'Edit the income source details',
  'كشف حساب': 'Account statement',
  'كل {{}}': 'Every {{}}',
  'كل {{}} {{}}': 'Every {{}} {{}}',
  'كل 3 أشهر': 'Every 3 months',
  'كل صديق يستخدم الكود المخصص لك، ستحصل أنت وهو على 7 أيام اشتراك برو مجاناً!': 'For every friend who uses your code, both of you will get 7 free days of Pro!',
  'كلمة المرور': 'Password',
  'كلمة المرور الجديدة': 'New password',
  'كلمة المرور يجب أن تكون 6 أحرف على الأقل': 'Password must be at least 6 characters',
  'كلمة مرور جديدة': 'New password',
  'كلمتا المرور غير متطابقتين': 'Passwords do not match',
  'كود الإحالة (اختياري)': 'Referral code (optional)',
  'كود الخصم (Promo Code)': 'Promo code',
  'لا توجد اختصارات. اضغط لإضافة اسم، فئة ومبلغ ثم استخدمها من هنا دون فتح النموذج.': 'No shortcuts yet. Tap to add a name, category, and amount, then use them from here without opening the form.',
  'لا توجد إنجازات بعد': 'No achievements yet',
  'لا توجد أهداف بعد': 'No goals yet',
  'لا توجد أي عمليات مسجلة في هذا التاريخ': 'No transactions recorded on this date',
  'لا توجد إيرادات مسجلة': 'No income records',
  'لا توجد بيانات جديدة': 'No new data',
  'لا توجد بيانات للشهر المحدد': 'No data for the selected month',
  'لا توجد بيانات لهذا الشهر': 'No data for this month',
  'لا توجد تحديات بعد': 'No challenges yet',
  'لا توجد تحليلات حالياً': 'No insights available right now',
  'لا توجد حصالات بعد': 'No savings wallets yet',
  'لا توجد خطة حالياً': 'No plan available right now',
  'لا توجد ديون مسجلة': 'No recorded debts',
  'لا توجد عمليات لهذا الشخص': 'No transactions for this person',
  'لا توجد عمليات مضافة مؤخراً': 'No recently added transactions',
  'لا توجد فئات': 'No categories',
  'لا توجد فواتير': 'No bills',
  'لا توجد مصادر': 'No sources',
  'لا توجد مصاريف متكررة': 'No recurring expenses',
  'لا توجد مصاريف مسجلة': 'No recorded expenses',
  'لا توجد ميزانيات محددة': 'No budgets set',
  'لا توجد نتائج': 'No results',
  'لا توجد نتائج لهذه الفئة': 'No results for this category',
  'لا يمكن تعديل الدين بعد سداده بالكامل.': 'The debt cannot be edited after it is fully paid.',
  'لا يمكن تعديل سعر الصرف للدولار مع نفسه': 'You cannot edit the exchange rate of the dollar against itself',
  'لا يمكن فتح تطبيق البريد الإلكتروني': 'Unable to open the email app',
  'لا يوجد أشخاص': 'No people',
  'لا يوجد بريد إلكتروني': 'No email address',
  'لحفظ بياناتك وموعد ميزانيتك': 'To save your data and budget schedule',
  'لديك': 'You have',
  'لديك حساب بالفعل؟': 'Already have an account?',
  'لسنة': 'for the year',
  'لم تتم المشاركة': 'Share was not completed',
  'لم يتم اختيار هدف': 'No goal selected',
  'لهذا الشهر': 'For this month',
  'لهذا اليوم': 'For today',
  'لي •': 'Owed to me •',
  'ليس لديك حساب؟': 'Don’t have an account?',
  'م': 'PM',
  'ماذا اشتريت؟': 'What did you buy?',
  'مارس': 'March',
  'مؤشر الصحة المالية': 'Financial health score',
  'مايو': 'May',
  'مبروك! حصلت على {{}} أيام إضافية في اشتراك برو.': 'Congratulations! You got {{}} extra days of Pro.',
  'مبلغ تستحق دفعه لـ:': 'Amount you need to pay to:',
  'مبلغ يستحق لك من:': 'Amount owed to you by:',
  'مستخدم دنانير': 'Dnanir User',
  'متأخرة {{}} يوم': '{{}} days overdue',
  'متبقي': 'Remaining',
  'متبقي {{}} يوم': '{{}} days left',
  'مثال: توفير لسيارة جديدة': 'Example: Save for a new car',
  'مُدعم بالذكاء الاصطناعي': 'AI-powered',
  'مدعوم بالذكاء الاصطناعي': 'Powered by AI',
  'مدفوع': 'Paid',
  'مدفوعة': 'paid',
  'مزامنة': 'Sync',
  'مزامنة البيانات': 'Data sync',
  'مزامنة البيانات تلقائياً عند فتح التطبيق (مميز)': 'Sync data automatically when opening the app (Premium)',
  'مزامنة البيانات متاحة للمشتركين المميزين فقط.': 'Data sync is available for premium users only.',
  'مزامنة البيانات متاحة للمشتركين المميزين فقط. يجب أن يكون نوع حسابك أو اشتراكك مميزاً لاستخدام المزامنة.': 'Data sync is available for premium users only. Your account or subscription must be premium to use sync.',
  'مزامنة تلقائية': 'Auto sync',
  'مستحقة اليوم': 'Due today',
  'مسح الفلاتر': 'Clear filters',
  'مسح الكل': 'Clear all',
  'مشاركة': 'Share',
  'مشاركة التطبيق': 'Share app',
  'مشاركة الكود مع الأصدقاء': 'Share your code with friends',
  'مصادر الدخل': 'Income sources',
  'مصدر افتراضي': 'Default source',
  'مصدر الدخل (مثال: مكافأة)': 'Income source (e.g. bonus)',
  'مصدر مخصص': 'Custom source',
  'مصروف جديد': 'New expense',
  'معاملة': 'transaction',
  'معدل الادخار': 'Savings rate',
  'مقارنة الأداء': 'Performance comparison',
  'مقارنة النشاط': 'Activity comparison',
  'مقارنة مع الشهر السابق': 'Compared with last month',
  'ملاحظات': 'Notes',
  'ملاحظات إضافية': 'Additional notes',
  'ملاحظات إضافية...': 'Additional notes...',
  'ملاحظات...': 'Notes...',
  'ملخص التقرير': 'Report summary',
  'ملخص اليوم': 'Today summary',
  'ملخصي المالي - {{}}': 'My financial summary - {{}}',
  'من': 'From',
  'من إجمالي الدخل': 'Of total income',
  'من المكتبة': 'From library',
  'من تاريخ': 'From date',
  'موعد الاستحقاق (اختياري)': 'Due date (optional)',
  'موعد الاستحقاق النهائي': 'Final due date',
  'نسبة السداد': 'Payment progress',
  'نسخ احتياطي': 'Backup',
  'نسخ احتياطي داخلي': 'Local backup',
  'نسخ المعرف': 'Copy ID',
  'نسخ معرف المستخدم': 'Copy user ID',
  'نسيت كلمة المرور': 'Forgot password',
  'نسيت كلمة المرور؟': 'Forgot password?',
  'نشط': 'Active',
  'نصائح ذكية': 'Smart tips',
  'نصائح ذكية للتوفير': 'Smart saving tips',
  'نعم، حذف': 'Yes, delete',
  'نهاية القائمة': 'End of list',
  'نوع الالتزام': 'Obligation type',
  'نوع الهدف': 'Goal type',
  'نوفمبر': 'November',
  'هدف': 'Goal',
  'هل أنت متأكد من حذف الفاتورة "{{}}"؟': 'Are you sure you want to delete the bill "{{}}"?',
  'هل أنت متأكد من حذف هذا الالتزام وجميع السجلات الملحقة به؟ هذا الإجراء لا يمكن التراجع عنه.': 'Are you sure you want to delete this obligation and all related records? This action cannot be undone.',
  'هل أنت متأكد من حذف هذا التحدي؟': 'Are you sure you want to delete this challenge?',
  'هل أنت متأكد من حذف هذا الحساب؟ لن يتم حذف الديون المرتبطة به ولكن سيتم فك ارتباطها بهذا الاسم.': 'Are you sure you want to delete this account? Related debts will not be deleted, but they will no longer be linked to this name.',
  'هل أنت متأكد من حذف هذا الدين؟ سيتم حذف جميع الأقساط المرتبطة به.': 'Are you sure you want to delete this debt? All related installments will be deleted.',
  'هل أنت متأكد من حذف هذا المصروف المتكرر؟': 'Are you sure you want to delete this recurring expense?',
  'هل أنت متأكد من حذف هذه الميزانية؟ لا يمكن التراجع عن هذا الإجراء.': 'Are you sure you want to delete this budget? This action cannot be undone.',
  'هل تريد حذف "{{}}"؟': 'Do you want to delete "{{}}"?',
  'هل تريد حذف هذه الصورة؟': 'Do you want to delete this image?',
  'هل لديك كود إحالة؟ أدخله هنا': 'Do you have a referral code? Enter it here',
  'وصف (اختياري)': 'Description (optional)',
  'وصلت لحدك الشهري (مرة واحدة للمجاني). ترقية الحساب تمنحك المزيد من التحليلات.': 'You reached your monthly limit (once for free users). Upgrading gives you more analyses.',
  'وصلت للحد الشهري للتحليل الذكي (10 مرات). يجدد الحد كل شهر.': 'You reached the monthly smart analysis limit (10 times). The limit resets every month.',
  'يجب تسجيل الدخول أو إنشاء حساب لاستخدام خطة الهدف بالذكاء الاصطناعي.': 'You need to sign in or create an account to use the AI goal plan.',
  'يجب تسجيل الدخول لاستخدام التحليل الذكي بمساعدة الذكاء الاصطناعي.': 'You need to sign in to use AI-powered smart analysis.',
  'يرجى اختيار فئة للميزانية': 'Please choose a category for the budget',
  'يرجى إدخال الاسم': 'Please enter the name',
  'يرجى إدخال رقم الهاتف': 'Please enter the phone number',
  'يرجى إدخال رمز التحقق المكون من 6 أرقام': 'Please enter the 6-digit verification code',
  'يرجى إدخال سعر صرف صحيح': 'Please enter a valid exchange rate',
  'يرجى إدخال عنوان الفاتورة': 'Please enter the bill title',
  'يرجى إدخال عنوان المصروف': 'Please enter the expense title',
  'يرجى إدخال عنوان الهدف': 'Please enter the goal title',
  'يرجى إدخال عنوان للحصالة': 'Please enter a title for the savings wallet',
  'يرجى إدخال كلمة مرور صحيحة (6 أحرف على الأقل)': 'Please enter a valid password (at least 6 characters)',
  'يرجى إدخال مبلغ الميزانية': 'Please enter the budget amount',
  'يرجى إدخال مبلغ صحيح': 'Please enter a valid amount',
  'يرجى إدخال مبلغ مستهدف صحيح': 'Please enter a valid target amount',
  'يرجى إدخال مصدر الدخل': 'Please enter the income source',
  'يرجى السماح بالإشعارات من إعدادات التطبيق': 'Please allow notifications from the app settings',
  'يرجى السماح بالوصول إلى الكاميرا والمكتبة من إعدادات التطبيق': 'Please allow access to the camera and library from the app settings',
  'يرجى تثبيت تطبيق WhatsApp': 'Please install WhatsApp',
  'يرجى التحقق من الهوية لحذف جميع البيانات': 'Please verify your identity to delete all data',
  'يستحق عليك': 'You owe',
  'يستحق عليك (لي)': 'You owe (to me)',
  'يستحق لك': 'Owed to you',
  'يستحق لك (لي)': 'Owed to you (to me)',
  'يناير': 'January',
  'يوليو': 'July',
  'يوم': 'Day',
  'يومي': 'Daily',
  'يونيو': 'June',
  'أهلاً': 'Hello',
  'إيجار': 'Rent',
  'الأحد': 'Sunday',
  'الاثنين': 'Monday',
  'الثلاثاء': 'Tuesday',
  'الأربعاء': 'Wednesday',
  'الخميس': 'Thursday',
  'الجمعة': 'Friday',
  'السبت': 'Saturday',
  'الانضباط': 'Discipline',
  'إنترنت': 'Internet',
  'أسبوعي': 'Weekly',
  'اشتراكات': 'Subscriptions',
  'تأمين': 'Insurance',
  'تقليل الصرف': 'Reduce spending',
  'تسديد جزء من الدين': 'Partial debt payment',
  'ج': 'Fr',
  'جيد': 'Good',
  'ح': 'Su',
  'خ': 'Th',
  'رحلة': 'Vacation',
  'ربع سنوي': 'Quarterly',
  'ر': 'We',
  'س': 'Sa',
  'سيارة': 'Car',
  'صباح الخير': 'Good morning',
  'طوارئ': 'Emergency',
  'غير محدد': 'Not set',
  'فشل الإضافة': 'Add failed',
  'فواتير الخدمات': 'Utility bills',
  'قرض': 'Loan',
  'هاتف': 'Phone',
  'مساء الخير': 'Good evening',
  'منزل': 'House',
  'ممتاز': 'Excellent',
  'المستخدم': 'User',
  'يحتاج تحسين': 'Needs improvement',
  'ث': 'Tu',
  'زواج': 'Wedding',
  ' (متأخر)': ' (Overdue)',
};

const actionTranslations: Record<string, string> = {
  'اختيار الصورة': 'choosing the image',
  'إضافة التحدي': 'adding the challenge',
  'إضافة التحدي المخصص': 'adding the custom challenge',
  'إضافة المبلغ': 'adding the amount',
  'إعادة فتح التحدي': 'reopening the challenge',
  'إكمال التحدي': 'completing the challenge',
  'الحذف': 'deleting',
  'العملية': 'processing',
  'إنشاء التقرير': 'creating the report',
  'تحديث التحدي': 'updating the challenge',
  'تحديث التقدم': 'updating the progress',
  'تحديث حالة الفاتورة': 'updating the bill status',
  'تحميل البيانات': 'loading the data',
  'تحميل الفئات': 'loading the categories',
  'تحميل الميزانيات': 'loading the budgets',
  'تحميل بيانات الدين': 'loading the debt data',
  'تحميل بيانات الفاتورة': 'loading the bill data',
  'تحميل الرؤى': 'loading insights',
  'تحويل العملة': 'converting the currency',
  'تسجيل التسديد': 'recording the payment',
  'تسجيل تسديد القسط': 'recording the installment payment',
  'تصدير التقرير': 'exporting the report',
  'تصدير PDF': 'exporting the PDF',
  'تغيير العملة': 'changing the currency',
  'حذف الإيراد': 'deleting the income entry',
  'حذف التحدي': 'deleting the challenge',
  'حذف الحصالة': 'deleting the savings wallet',
  'حذف الدين': 'deleting the debt',
  'حذف الفئة': 'deleting the category',
  'حذف الفاتورة': 'deleting the bill',
  'حذف المصروف': 'deleting the expense',
  'حذف الميزانية': 'deleting the budget',
  'حذف الهدف': 'deleting the goal',
  'حفظ البيانات': 'saving the data',
  'حفظ الفاتورة': 'saving the bill',
  'حفظ الفئة': 'saving the category',
  'حفظ الميزانية': 'saving the budget',
  'حفظ الهدف': 'saving the goal',
  'حفظ سعر الصرف': 'saving the exchange rate',
  'دفع الدين': 'paying the debt',
  'دفع القسط': 'paying the installment',
  'عملية التحويل': 'processing the transfer',
  'فتح البريد الإلكتروني': 'opening the email app',
  'فتح WhatsApp': 'opening WhatsApp',
  'مسح البيانات': 'clearing the data',
  'إرسال رمز التحقق': 'sending the verification code',
  'إعادة التعيين': 'resetting',
  'إعادة إرسال رمز التحقق': 'resending the verification code',
  'تسجيل الدخول': 'signing in',
};

const failureTranslations: Record<string, string> = {
  'الإضافة': 'Add failed',
  'إنشاء الحساب': 'Failed to create the account',
  'إنشاء الخطة': 'Failed to create the plan',
  'إرسال رمز التحقق': 'Failed to send the verification code',
  'إعادة إرسال رمز التحقق': 'Failed to resend the verification code',
  'إعادة تعيين كلمة المرور': 'Failed to reset the password',
  'تسجيل الدخول': 'Failed to sign in',
};

const translateFragment = (text: string): string => {
  return exactLiteralEn[text] || text;
};

const translateLiteralToEnglish = (text: string): string => {
  if (exactLiteralEn[text]) {
    return exactLiteralEn[text];
  }

  let match = text.match(/^حدث خطأ أثناء (.+)$/);
  if (match) {
    return `An error occurred while ${actionTranslations[match[1]] || translateFragment(match[1])}`;
  }

  match = text.match(/^فشل (.+)$/);
  if (match) {
    return failureTranslations[match[1]] || `Failed: ${translateFragment(match[1])}`;
  }

  match = text.match(/^تم إضافة (.+) بنجاح$/);
  if (match) {
    return `${translateFragment(match[1])} added successfully`;
  }

  match = text.match(/^تم تحديث (.+) بنجاح$/);
  if (match) {
    return `${translateFragment(match[1])} updated successfully`;
  }

  match = text.match(/^تم حذف (.+) بنجاح$/);
  if (match) {
    return `${translateFragment(match[1])} deleted successfully`;
  }

  match = text.match(/^يرجى إدخال (.+)$/);
  if (match) {
    return `Please enter ${translateFragment(match[1])}`;
  }

  match = text.match(/^أدخل (.+)$/);
  if (match) {
    return `Enter ${translateFragment(match[1])}`;
  }

  match = text.match(/^اختر (.+)$/);
  if (match) {
    return `Choose ${translateFragment(match[1])}`;
  }

  return text;
};

export const literalEn: Record<string, string> = Object.fromEntries(
  Array.from(new Set([...Object.keys(literalAr), ...Object.keys(exactLiteralEn)])).map((key) => [key, translateLiteralToEnglish(key)]),
);
