export interface Country {
    name: string;
    code: string;
    dial: string;
}

export const COUNTRIES: Country[] = [
    { name: 'العراق', code: 'IQ', dial: '+964' },
    { name: 'السعودية', code: 'SA', dial: '+966' },
    { name: 'الإمارات', code: 'AE', dial: '+971' },
    { name: 'الكويت', code: 'KW', dial: '+965' },
    { name: 'قطر', code: 'QA', dial: '+974' },
    { name: 'عمان', code: 'OM', dial: '+968' },
    { name: 'البحرين', code: 'BH', dial: '+973' },
    { name: 'الأردن', code: 'JO', dial: '+962' },
    { name: 'لبنان', code: 'LB', dial: '+961' },
    { name: 'سوريا', code: 'SY', dial: '+963' },
    { name: 'فلسطين', code: 'PS', dial: '+970' },
    { name: 'مصر', code: 'EG', dial: '+20' },
    { name: 'ليبيا', code: 'LY', dial: '+218' },
    { name: 'تونس', code: 'TN', dial: '+216' },
    { name: 'الجزائر', code: 'DZ', dial: '+213' },
    { name: 'المغرب', code: 'MA', dial: '+212' },
    { name: 'السودان', code: 'SD', dial: '+249' },
    { name: 'اليمن', code: 'YE', dial: '+967' },
    { name: 'تركيا', code: 'TR', dial: '+90' },
    { name: 'إيران', code: 'IR', dial: '+98' },
    { name: 'الولايات المتحدة', code: 'US', dial: '+1' },
    { name: 'كندا', code: 'CA', dial: '+1' },
    { name: 'المملكة المتحدة', code: 'GB', dial: '+44' },
    { name: 'ألمانيا', code: 'DE', dial: '+49' },
    { name: 'فرنسا', code: 'FR', dial: '+33' },
    { name: 'السويد', code: 'SE', dial: '+46' },
    { name: 'النرويج', code: 'NO', dial: '+47' },
    { name: 'هولندا', code: 'NL', dial: '+31' },
    { name: 'بلجيكا', code: 'BE', dial: '+32' },
    { name: 'سويسرا', code: 'CH', dial: '+41' },
    { name: 'النمسا', code: 'AT', dial: '+43' },
    { name: 'إيطاليا', code: 'IT', dial: '+39' },
    { name: 'إسبانيا', code: 'ES', dial: '+34' },
    { name: 'اليونان', code: 'GR', dial: '+30' },
    { name: 'قبرص', code: 'CY', dial: '+357' },
    { name: 'أستراليا', code: 'AU', dial: '+61' },
    { name: 'ماليزيا', code: 'MY', dial: '+60' },
    { name: 'إندونيسيا', code: 'ID', dial: '+62' },
    { name: 'الهند', code: 'IN', dial: '+91' },
    { name: 'باكستان', code: 'PK', dial: '+92' },
    { name: 'روسيا', code: 'RU', dial: '+7' },
    { name: 'الصين', code: 'CN', dial: '+86' },
    { name: 'اليابان', code: 'JP', dial: '+81' },
    { name: 'كوريا الجنوبية', code: 'KR', dial: '+82' },
    { name: 'البرازيل', code: 'BR', dial: '+55' },
    { name: 'المكسيك', code: 'MX', dial: '+52' },
    { name: 'نيجيريا', code: 'NG', dial: '+234' },
    { name: 'جنوب أفريقيا', code: 'ZA', dial: '+27' },
    { name: 'موريتانيا', code: 'MR', dial: '+222' },
    { name: 'جيبوتي', code: 'DJ', dial: '+253' },
    { name: 'الصومال', code: 'SO', dial: '+252' },
    { name: 'جزر القمر', code: 'KM', dial: '+269' },
    { name: 'جنوب السودان', code: 'SS', dial: '+211' },
    { name: 'أذربيجان', code: 'AZ', dial: '+994' },
    { name: 'جورجيا', code: 'GE', dial: '+995' },
    { name: 'أوزبكستان', code: 'UZ', dial: '+998' },
    { name: 'كازاخستان', code: 'KZ', dial: '+7' },
];
